import { ShotFigure } from "./ShotFigure";

export type Shot = { src: string; alt: string; caption: string };

/**
 * "See it in action" section — real product screenshots (framed + branded,
 * generated by the marketing capture harness) shown as a lead shot + a grid.
 * Server component; each figure delegates to ShotFigure, which adds the
 * click-to-enlarge lightbox on the client.
 */
export function DemoShowcase({
  eyebrow,
  title,
  subtitle,
  shots,
}: {
  eyebrow: string;
  title: string;
  subtitle: string;
  shots: Shot[];
}) {
  const [lead, ...rest] = shots;
  if (!lead) return null;

  return (
    <section className="mx-auto max-w-7xl xl:max-w-[clamp(80rem,95vw,105rem)] px-4 pb-16 sm:px-6 sm:pb-20">
      <div className="mb-10 text-center">
        <p className="text-[12px] font-bold tracking-wide text-purple-300">
          {eyebrow}
        </p>
        <h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">{title}</h2>
        <p className="mx-auto mt-4 max-w-2xl text-base leading-7 text-gray-400">{subtitle}</p>
      </div>

      <div className="mx-auto mb-6 max-w-4xl">
        {/* The lead renders at ~896px, which is already readable, so it does
            not offer the lightbox. The grid shots below are ~368px and do. */}
        <ShotFigure
          shot={lead}
          sizes="(min-width: 1024px) 56rem, 100vw"
          rounded="rounded-3xl"
          zoomable={false}
        />
      </div>

      {/* A single supporting shot centres on its own; 3 sit balanced in a row;
          2 or 4 fall into an even 2-column grid. Everything stays centred. */}
      {rest.length === 1 && (
        <div className="mx-auto max-w-3xl">
          <ShotFigure shot={rest[0]} sizes="(min-width: 768px) 48rem, 100vw" />
        </div>
      )}

      {rest.length > 1 && (
        <div
          className={`mx-auto grid max-w-6xl gap-6 ${
            rest.length === 3 ? "sm:grid-cols-3" : "sm:grid-cols-2"
          }`}
        >
          {/* sizes has to match the real rendered width or the browser picks a
              source that gets upscaled. The grid is max-w-6xl (1152px) with
              24px gaps: 3 columns land at ~368px each, 2 columns at ~564px. */}
          {rest.map((s) => (
            <ShotFigure
              key={s.src}
              shot={s}
              sizes={
                rest.length === 3
                  ? "(min-width: 640px) 23rem, 100vw"
                  : "(min-width: 640px) 35rem, 100vw"
              }
            />
          ))}
        </div>
      )}
    </section>
  );
}
