import Image from "next/image";

export type Shot = { src: string; alt: string; caption: string };

/**
 * "See it in action" section — real product screenshots (framed + branded,
 * generated by the marketing capture harness) shown as a lead shot + a grid.
 * Server component; uses next/image for responsive WebP delivery.
 */
export function DemoShowcase({
  eyebrow,
  title,
  subtitle,
  shots,
}: {
  eyebrow: string;
  title: string;
  subtitle: string;
  shots: Shot[];
}) {
  const [lead, ...rest] = shots;
  if (!lead) return null;

  return (
    <section className="mx-auto max-w-7xl px-4 pb-16 sm:px-6 sm:pb-20">
      <div className="mb-10 text-center">
        <p className="text-[11px] font-bold tracking-wide text-purple-300/90">
          {eyebrow}
        </p>
        <h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">{title}</h2>
        <p className="mx-auto mt-4 max-w-2xl text-base leading-7 text-gray-400">{subtitle}</p>
      </div>

      <figure className="mx-auto mb-6 max-w-4xl">
        <div className="overflow-hidden rounded-3xl ring-1 ring-white/10">
          <Image
            src={lead.src}
            alt={lead.alt}
            width={2000}
            height={1370}
            sizes="(min-width: 1024px) 56rem, 100vw"
            className="h-auto w-full"
          />
        </div>
        <figcaption className="mt-3 text-center text-sm leading-6 text-gray-400">
          {lead.caption}
        </figcaption>
      </figure>

      {/* A single supporting shot centres on its own; 3 sit balanced in a row;
          2 or 4 fall into an even 2-column grid. Everything stays centred. */}
      {rest.length === 1 && (
        <figure className="mx-auto max-w-3xl">
          <div className="overflow-hidden rounded-2xl ring-1 ring-white/10">
            <Image
              src={rest[0].src}
              alt={rest[0].alt}
              width={2000}
              height={1370}
              sizes="(min-width: 768px) 48rem, 100vw"
              className="h-auto w-full"
            />
          </div>
          <figcaption className="mt-3 text-center text-sm leading-6 text-gray-400">
            {rest[0].caption}
          </figcaption>
        </figure>
      )}

      {rest.length > 1 && (
        <div
          className={`mx-auto grid max-w-6xl gap-6 ${
            rest.length === 3 ? "sm:grid-cols-3" : "sm:grid-cols-2"
          }`}
        >
          {rest.map((s) => (
            <figure key={s.src}>
              <div className="overflow-hidden rounded-2xl ring-1 ring-white/10">
                <Image
                  src={s.src}
                  alt={s.alt}
                  width={2000}
                  height={1370}
                  sizes="(min-width: 640px) 22rem, 100vw"
                  className="h-auto w-full"
                />
              </div>
              <figcaption className="mt-3 text-center text-sm leading-6 text-gray-400">
                {s.caption}
              </figcaption>
            </figure>
          ))}
        </div>
      )}
    </section>
  );
}
