export const visemeMap: Record<number, Record<string, number>> = {
  0: { viseme_sil: 1 },
  1: { viseme_PP: 1 },
  2: { viseme_FF: 1 },
  3: { viseme_TH: 1 },
  4: { viseme_DD: 1 },
  5: { viseme_kk: 1 },
  6: { viseme_CH: 1 },
  7: { viseme_SS: 1 },
  8: { viseme_nn: 1 },
  9: { viseme_RR: 1 },
  10: { viseme_aa: 1 },
  11: { viseme_E: 1 },
  12: { viseme_I: 1 },
  13: { viseme_O: 1 },
  14: { viseme_U: 1 },
  15: { viseme_sil: 1 },
  16: { viseme_sil: 1 },
  17: { viseme_sil: 1 },
  18: { viseme_sil: 1 },
  19: { viseme_sil: 1 },
  20: { viseme_sil: 1 },
  21: { viseme_sil: 1 },
};