import Link from "next/link";
import type { Metadata } from "next";
import { GlassCard, MarketingShell, SectionHeading } from "@/app/components/marketing/MarketingShell";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: "Terms of use for AI Career Mentor — an AI interview coaching and practice platform. Read about acceptable use, AI limitations and candidate responsibilities.",
};

const coreSections = [
  {
    title: "What AI Career Mentor is",
    text: "AI Career Mentor is an interview coaching and preparation tool. It helps you practise answers, review delivery and identify areas for improvement. It is not a hiring service, recruitment agency or employment platform.",
  },
  {
    title: "AI-generated feedback",
    text: "Feedback, scores, summaries and model answers are generated by AI. They should be used as preparation guidance only. Always apply your own judgement and adapt any suggested wording honestly to your real experience.",
  },
  {
    title: "Candidate responsibility",
    text: "You are responsible for the content you upload, type or say during practice. Do not upload confidential employer data, third-party personal data or information you do not have the right to share.",
  },
  {
    title: "Service availability",
    text: "We aim to provide a reliable experience. However, AI Career Mentor may occasionally be unavailable due to maintenance, third-party service issues or technical errors. Uninterrupted access cannot be guaranteed.",
  },
  {
    title: "Account access",
    text: "You are responsible for keeping your account credentials secure. Do not share access to your account. We may suspend or terminate access if these terms are violated.",
  },
  {
    title: "Changes to the service",
    text: "We may update or change features, pricing or these terms at any time. We will notify registered users of material changes. Continued use after changes constitutes acceptance.",
  },
];

const responsibleUse = [
  "Use feedback as preparation guidance, not as a guaranteed outcome.",
  "Keep answers truthful and based on your real work, study or life experience.",
  "Review AI-generated model answers before using any wording in a real interview.",
  "Avoid uploading documents containing unnecessary sensitive or third-party data.",
  "Check browser microphone and camera permissions before live practice sessions.",
  "Do not attempt to reverse-engineer, extract or abuse the platform's AI systems.",
  "Do not use the service to generate content that is false, harmful or deceptive.",
];

const limitations = [
  {
    title: "No hiring decisions",
    text: "AI Career Mentor does not make hiring decisions and is not connected to any employer's recruitment process. Scores are internal coaching signals only.",
  },
  {
    title: "No employment guarantee",
    text: "Using the platform does not guarantee interview success, job offers or any particular outcome. Results depend on your preparation, interview context and the employer's own process.",
  },
  {
    title: "AI accuracy",
    text: "AI feedback may be incomplete, imprecise or unsuitable for your specific role or employer. Treat it as one input among many — not as authoritative career advice.",
  },
  {
    title: "Limitation of liability",
    text: "To the fullest extent permitted by law, AI Career Mentor is provided as-is. We are not liable for decisions made based on AI feedback, lost opportunities or any indirect or consequential loss.",
  },
];

export default function TermsPage() {
  return (
    <MarketingShell currentPath="/">
      <section className="mx-auto max-w-7xl px-4 pb-6 pt-8 sm:px-6 sm:pb-10 sm:pt-12">
        <div className="overflow-hidden rounded-[2.25rem] border border-white/10 bg-white/[0.065] p-6 shadow-2xl shadow-purple-950/20 backdrop-blur-2xl sm:p-8 md:p-10">
          <div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-white/50 to-transparent" />

          <div className="max-w-4xl">
            <p className="mb-3 text-sm font-black uppercase tracking-[0.25em] text-purple-300">
              Terms of use
            </p>
            <h1 className="text-4xl font-black leading-[1.02] tracking-[-0.055em] md:text-5xl">
              Use AI Career Mentor as a preparation tool, not a guarantee.
            </h1>
            <p className="mt-5 max-w-3xl text-base leading-8 text-gray-300 md:text-lg">
              These terms explain how AI Career Mentor may be used, what you can
              expect from the platform, what we do not provide, and your
              responsibilities as a user.
            </p>

            <p className="mt-5 rounded-2xl border border-amber-300/15 bg-amber-300/10 p-4 text-sm leading-6 text-amber-100">
              Last updated: May 2026. By using AI Career Mentor you agree to
              these terms. For questions, contact{" "}
              <span className="font-bold text-amber-50">
                support@aicareermentor.co.uk
              </span>
              .
            </p>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-4 pb-8 sm:px-6 sm:pb-12">
        <div className="grid gap-6 lg:grid-cols-[1.15fr_0.85fr]">
          <div className="space-y-6">

            <GlassCard>
              <SectionHeading
                eyebrow="Core terms"
                title="How the service works."
                description="These terms apply to all users of AI Career Mentor."
              />
              <div className="mt-6 grid gap-4 md:grid-cols-2">
                {coreSections.map((section) => (
                  <div
                    key={section.title}
                    className="rounded-[1.5rem] border border-white/10 bg-black/25 p-5"
                  >
                    <h3 className="mb-2 font-black text-white">{section.title}</h3>
                    <p className="text-sm leading-7 text-gray-400">{section.text}</p>
                  </div>
                ))}
              </div>
            </GlassCard>

            <GlassCard>
              <SectionHeading
                eyebrow="Limitations"
                title="What we do not provide."
                description="Please read these carefully before relying on AI-generated feedback."
              />
              <div className="mt-6 grid gap-4 sm:grid-cols-2">
                {limitations.map((item) => (
                  <div
                    key={item.title}
                    className="rounded-[1.5rem] border border-white/10 bg-black/25 p-5"
                  >
                    <h3 className="mb-2 font-black text-white">{item.title}</h3>
                    <p className="text-sm leading-7 text-gray-400">{item.text}</p>
                  </div>
                ))}
              </div>
            </GlassCard>

            <GlassCard>
              <SectionHeading
                eyebrow="Uploads and content"
                title="What you upload to AI Career Mentor."
              />
              <div className="mt-5 space-y-4 text-sm leading-7 text-gray-300">
                <p>
                  You should only upload or enter information that you are
                  comfortable using for interview practice. This includes CV
                  text, role specifications and interview goal notes.
                </p>
                <p>
                  Uploaded files (PDF, Word, text) are converted into plain
                  text for personalisation. Extracted text may not perfectly
                  reproduce the original document, particularly for
                  complex-formatted CVs.
                </p>
                <p>
                  Do not upload documents containing confidential employer
                  information, third-party personal data, or sensitive
                  information that is not necessary for interview preparation.
                </p>
                <p>
                  AI Career Mentor does not retain raw uploaded files. Only
                  extracted text that you choose to save to your profile is
                  stored.
                </p>
              </div>
            </GlassCard>

            <GlassCard>
              <SectionHeading
                eyebrow="Intellectual property"
                title="Ownership of content."
              />
              <div className="mt-5 space-y-4 text-sm leading-7 text-gray-300">
                <p>
                  The AI Career Mentor platform, its design, copy, AI coaching
                  systems and technology are owned by or licensed to AI Career
                  Mentor.
                </p>
                <p>
                  You retain ownership of any personal content you provide (CV
                  text, answers, goals). By using the platform, you grant AI
                  Career Mentor a limited licence to process that content to
                  deliver the service.
                </p>
                <p>
                  AI-generated feedback, model answers and session summaries are
                  provided for your personal preparation use. Do not redistribute
                  or resell AI-generated outputs.
                </p>
              </div>
            </GlassCard>

            <GlassCard>
              <SectionHeading
                eyebrow="Governing law"
                title="Jurisdiction and disputes."
              />
              <div className="mt-5 space-y-4 text-sm leading-7 text-gray-300">
                <p>
                  These terms are governed by the laws of England and Wales. Any
                  disputes arising under these terms shall be subject to the
                  exclusive jurisdiction of the courts of England and Wales.
                </p>
                <p>
                  If any provision of these terms is found to be unenforceable,
                  the remaining provisions will continue to apply.
                </p>
              </div>
            </GlassCard>

          </div>

          <aside className="space-y-6">
            <GlassCard>
              <p className="mb-4 text-sm font-black uppercase tracking-[0.2em] text-purple-300">
                Responsible use checklist
              </p>
              <div className="space-y-3 text-sm leading-6 text-gray-400">
                {responsibleUse.map((item) => (
                  <p key={item} className="flex gap-2">
                    <span className="mt-0.5 text-purple-400">✓</span>
                    <span>{item}</span>
                  </p>
                ))}
              </div>
            </GlassCard>

            <GlassCard>
              <p className="mb-4 text-sm font-black uppercase tracking-[0.2em] text-cyan-300">
                Quick links
              </p>
              <div className="space-y-3">
                <Link href="/practice">
                  <button className="w-full rounded-2xl bg-gradient-to-r from-purple-500 via-fuchsia-500 to-blue-500 px-5 py-3 text-sm font-black text-white shadow-2xl shadow-purple-900/35 transition hover:scale-[1.01]">
                    Start practice
                  </button>
                </Link>
                <Link href="/privacy">
                  <button className="w-full rounded-2xl border border-cyan-300/20 bg-cyan-300/10 px-5 py-3 text-sm font-black text-cyan-100 transition hover:bg-cyan-300/15">
                    Privacy policy
                  </button>
                </Link>
                <Link href="/profile">
                  <button className="w-full rounded-2xl border border-white/10 bg-white/[0.05] px-5 py-3 text-sm font-black text-white transition hover:bg-white/[0.09]">
                    Manage profile
                  </button>
                </Link>
              </div>
            </GlassCard>

            <GlassCard>
              <p className="mb-3 text-sm font-black uppercase tracking-[0.2em] text-purple-300">
                Contact
              </p>
              <div className="space-y-3 text-sm leading-6 text-gray-400">
                <p>
                  For questions about these terms or to report a concern,
                  contact us at:
                </p>
                <p className="font-bold text-gray-200">
                  support@aicareermentor.co.uk
                </p>
              </div>
            </GlassCard>
          </aside>
        </div>
      </section>
    </MarketingShell>
  );
}
