import Link from "next/link";

const sections = [
  {
    title: "Use of the platform",
    text: "AI Career Mentor is an interview-practice and coaching tool. It can help you prepare answers, review delivery and identify improvement areas, but it does not guarantee job offers, interview outcomes or hiring decisions.",
  },
  {
    title: "AI-generated feedback",
    text: "Feedback, scores, summaries and model answers are generated by AI and should be treated as guidance. Always use your own judgement and adapt answers honestly to your real experience.",
  },
  {
    title: "Candidate responsibility",
    text: "You are responsible for the information you enter, upload or say during practice. Do not upload content you do not have the right to use, and do not include unnecessary sensitive information.",
  },
  {
    title: "Availability",
    text: "The product may occasionally be unavailable because of maintenance, browser permissions, network issues, third-party services or technical errors. We aim to provide a reliable experience, but uninterrupted access cannot be guaranteed.",
  },
];

const responsibleUse = [
  "Use feedback as preparation guidance, not as a guaranteed hiring outcome.",
  "Keep answers truthful and based on your real work, study or life experience.",
  "Review AI-generated model answers before using any wording in a real interview.",
  "Avoid uploading documents that contain unnecessary sensitive or third-party data.",
  "Check browser microphone and camera permissions before live practice sessions.",
];

export default function TermsPage() {
  return (
    <main className="min-h-screen overflow-hidden bg-[#07030d] text-white">
      <header className="sticky top-0 z-50 border-b border-white/10 bg-[#07030d]/85 backdrop-blur-2xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-3 sm:px-6 sm:py-4">
          <Link href="/" className="flex min-w-0 items-center gap-3">
            <div className="relative shrink-0">
              <div className="absolute -inset-2 rounded-2xl bg-purple-500/25 blur-xl" />
              <div className="relative rounded-2xl border border-white/15 bg-white/95 p-1 shadow-lg shadow-purple-950/40">
                <img
                  src="/brand/logo.jpg"
                  alt="AI Career Mentor"
                  className="h-10 w-10 rounded-xl object-contain sm:h-11 sm:w-11"
                />
              </div>
            </div>

            <div className="min-w-0">
              <p className="truncate text-base font-black tracking-[-0.03em] sm:text-lg">
                AI Career Mentor
              </p>
              <p className="hidden text-xs font-medium text-purple-100/55 sm:block">
                Terms and responsible use
              </p>
            </div>
          </Link>

          <div className="flex shrink-0 items-center gap-2 sm:gap-3">
            <Link href="/practice">
              <button className="rounded-full bg-white px-4 py-2.5 text-sm font-black text-black shadow-xl shadow-purple-950/20 transition hover:bg-purple-100 sm:px-5">
                Start Practice
              </button>
            </Link>
          </div>
        </div>
      </header>

      <div className="relative">
        <div className="pointer-events-none absolute left-1/2 top-[-260px] h-[620px] w-[920px] -translate-x-1/2 rounded-full bg-purple-700/30 blur-[140px]" />
        <div className="pointer-events-none absolute right-[-220px] top-24 h-[460px] w-[460px] rounded-full bg-cyan-500/15 blur-[120px]" />
        <div className="pointer-events-none absolute left-[-220px] top-80 h-[420px] w-[420px] rounded-full bg-fuchsia-500/15 blur-[120px]" />

        <div className="relative mx-auto max-w-7xl px-4 py-8 sm:px-6 sm:py-12 lg:py-16">
          <section className="mb-8 overflow-hidden rounded-[2.25rem] border border-white/10 bg-white/[0.07] p-6 shadow-2xl shadow-purple-950/20 backdrop-blur-2xl sm:p-8 md:p-10">
            <div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-white/50 to-transparent" />

            <div className="relative max-w-4xl">
              <p className="mb-3 text-sm font-black uppercase tracking-[0.25em] text-purple-300">
                Terms and responsible use
              </p>
              <h1 className="text-4xl font-black leading-[1.02] tracking-[-0.055em] md:text-6xl">
                Use AI Career Mentor as a preparation tool, not a guarantee.
              </h1>
              <p className="mt-5 max-w-3xl text-base leading-8 text-gray-300 md:text-lg">
                This page explains the intended use of the platform in plain
                English. It helps set expectations for AI feedback, candidate
                responsibility and product availability.
              </p>

              <p className="mt-5 rounded-2xl border border-amber-300/15 bg-amber-300/10 p-4 text-sm leading-6 text-amber-100">
                This is a product terms draft, not formal legal advice. Before
                relying on it as your official terms of service, review it with a
                qualified professional and align it with your actual business,
                payment model and supplier setup.
              </p>
            </div>
          </section>

          <section className="grid gap-6 lg:grid-cols-[1.15fr_0.85fr]">
            <div className="space-y-6">
              <GlassSection title="Plain-English terms">
                <div className="grid gap-4 md:grid-cols-2">
                  {sections.map((section) => (
                    <div
                      key={section.title}
                      className="rounded-[1.5rem] border border-white/10 bg-black/25 p-5 shadow-xl shadow-black/10"
                    >
                      <h2 className="mb-2 text-lg font-black tracking-[-0.02em] text-white">
                        {section.title}
                      </h2>
                      <p className="text-sm leading-7 text-gray-400">
                        {section.text}
                      </p>
                    </div>
                  ))}
                </div>
              </GlassSection>

              <GlassSection title="AI feedback limitations">
                <div className="space-y-4 text-sm leading-7 text-gray-300">
                  <p>
                    AI feedback may be incomplete, imperfect or unsuitable for
                    your specific situation. It should be used to support your
                    preparation, not replace professional career advice, personal
                    judgement or employer-specific guidance.
                  </p>
                  <p>
                    Scores are intended to help you compare practice performance
                    and spot improvement areas. They are not official hiring
                    assessments and do not represent the view of any employer.
                  </p>
                </div>
              </GlassSection>

              <GlassSection title="Uploads, answers and profile content">
                <div className="space-y-4 text-sm leading-7 text-gray-300">
                  <p>
                    You should only upload or enter information that you are
                    comfortable using for interview practice. Do not upload
                    confidential employer data, third-party personal data or
                    sensitive information that is not needed for preparation.
                  </p>
                  <p>
                    If you use the profile builder, review the extracted document
                    text before saving. Uploaded files may be converted into text
                    for practice context, and extracted text may not always be
                    perfect.
                  </p>
                </div>
              </GlassSection>
            </div>

            <aside className="space-y-6">
              <GlassSection title="Responsible use checklist">
                <div className="space-y-3 text-sm leading-6 text-gray-400">
                  {responsibleUse.map((item) => (
                    <p key={item} className="flex gap-2">
                      <span className="text-purple-300">✓</span>
                      <span>{item}</span>
                    </p>
                  ))}
                </div>
              </GlassSection>

              <GlassSection title="Before publishing officially">
                <div className="space-y-3 text-sm leading-7 text-gray-400">
                  <p>
                    Add your company name, registered address, support contact,
                    payment terms, refund policy, cancellation terms and
                    jurisdiction-specific clauses if relevant.
                  </p>
                  <p>
                    Check the terms against your payment provider, authentication
                    provider, AI provider, database provider and production data
                    retention policy.
                  </p>
                </div>
              </GlassSection>

              <GlassSection title="Useful links">
                <div className="space-y-3">
                  <Link href="/privacy">
                    <button className="w-full rounded-2xl border border-cyan-300/20 bg-cyan-300/10 px-5 py-3 text-sm font-black text-cyan-100 transition hover:bg-cyan-300/15">
                      Privacy transparency
                    </button>
                  </Link>
                  <Link href="/practice">
                    <button className="w-full rounded-2xl bg-gradient-to-r from-purple-500 via-fuchsia-500 to-blue-500 px-5 py-3 text-sm font-black text-white shadow-2xl shadow-purple-900/35 transition hover:scale-[1.01]">
                      Start practice
                    </button>
                  </Link>
                  <Link href="/profile">
                    <button className="w-full rounded-2xl border border-purple-300/20 bg-purple-300/10 px-5 py-3 text-sm font-black text-purple-100 transition hover:bg-purple-300/15">
                      Manage profile
                    </button>
                  </Link>
                </div>
              </GlassSection>
            </aside>
          </section>
        </div>
      </div>
    </main>
  );
}

function GlassSection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-white/[0.065] p-5 shadow-2xl shadow-purple-950/10 backdrop-blur-2xl sm:p-6">
      <div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-white/40 to-transparent" />
      <div className="relative">
        <h2 className="mb-4 text-2xl font-black tracking-[-0.035em] text-white">
          {title}
        </h2>
        {children}
      </div>
    </section>
  );
}
