import Link from "next/link";
import type { Metadata } from "next";
import { CandidateShell } from "@/app/components/marketing/CandidateShell";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: "Terms of use for AI Career Mentor, an AI interview coaching and practice platform. Read about acceptable use, AI limitations and candidate responsibilities.",
};

const coreSections = [
  {
    title: "What AI Career Mentor is",
    text: "AI Career Mentor is an interview coaching and preparation tool. It helps you practise answers, review delivery and identify areas for improvement. It is not a hiring service, recruitment agency or employment platform.",
  },
  {
    title: "AI-generated feedback",
    text: "Feedback, scores, summaries and model answers are generated by AI. They should be used as preparation guidance only. Always apply your own judgement and adapt any suggested wording honestly to your real experience.",
  },
  {
    title: "Candidate responsibility",
    text: "You are responsible for the content you upload, type or say during practice. Do not upload confidential employer data, third-party personal data or information you do not have the right to share.",
  },
  {
    title: "Service availability",
    text: "We aim to provide a reliable experience. However, AI Career Mentor may occasionally be unavailable due to maintenance, third-party service issues or technical errors. Uninterrupted access cannot be guaranteed.",
  },
  {
    title: "Account access",
    text: "You are responsible for keeping your account credentials secure. Do not share access to your account. We may suspend or terminate access if these terms are violated.",
  },
  {
    title: "Changes to the service",
    text: "We may update or change features, pricing or these terms at any time. We will notify registered users of material changes. Continued use after changes constitutes acceptance.",
  },
];

const limitations = [
  {
    title: "No hiring decisions",
    text: "AI Career Mentor does not make hiring decisions and is not connected to any employer's recruitment process. Scores are internal coaching signals only.",
  },
  {
    title: "No employment guarantee",
    text: "Using the platform does not guarantee interview success, job offers or any particular outcome. Results depend on your preparation, interview context and the employer's own process.",
  },
  {
    title: "AI accuracy",
    text: "AI feedback may be incomplete, imprecise or unsuitable for your specific role or employer. Treat it as one input among many, not as authoritative career advice.",
  },
  {
    title: "Limitation of liability",
    text: "To the fullest extent permitted by law, AI Career Mentor is provided as-is. We are not liable for decisions made based on AI feedback, lost opportunities or any indirect or consequential loss.",
  },
];

const prohibitedUse = [
  { title: "Copying or cloning", text: "You must not copy, reproduce, replicate, or create derivative works based on the platform's design, code, UI, or functionality, whether in whole or in part." },
  { title: "Scraping and data extraction", text: "Automated scraping, crawling, indexing, or extraction of any platform content (including questions, feedback, prompts, or scoring logic) is strictly prohibited." },
  { title: "Reverse engineering", text: "You must not decompile, disassemble, reverse-engineer, or attempt to derive source code, AI prompts, algorithms, or scoring logic from the platform." },
  { title: "Competitive intelligence", text: "You must not access the platform for the purpose of building, benchmarking, or improving a competing product or service." },
  { title: "Unauthorised access", text: "You must not attempt to gain unauthorised access to any part of the platform, its infrastructure, or other users' accounts." },
  { title: "Resale or sublicensing", text: "You must not resell, sublicence, or provide third-party access to any part of the platform or its outputs without express written permission." },
];

const responsibleUse = [
  "Use feedback as preparation guidance, not as a guaranteed outcome.",
  "Keep answers truthful and based on your real work, study or life experience.",
  "Review AI-generated model answers before using any wording in a real interview.",
  "Avoid uploading documents containing unnecessary sensitive or third-party data.",
  "Check browser microphone and camera permissions before live practice sessions.",
  "Do not attempt to reverse-engineer, extract or abuse the platform's AI systems.",
  "Do not use the service to generate content that is false, harmful or deceptive.",
];

export default function TermsPage() {
  return (
    <CandidateShell currentPath="/terms">
      <div>
        {/* Hero */}
        <section className="mx-auto max-w-4xl px-4 pb-12 pt-1 text-center sm:px-6 sm:pt-3">
          <h1 className="mx-auto max-w-3xl text-[2.2rem] font-bold leading-[1.06] tracking-tight sm:text-4xl">
            Use AI Career Mentor as a{" "}
            <span className="text-violet-300">
              preparation tool.
            </span>
          </h1>
          <p className="mx-auto mt-5 max-w-xl text-base leading-8 text-gray-400">
            These terms explain how AI Career Mentor may be used, what you can
            expect from the platform, what we do not provide, and your
            responsibilities as a user.
          </p>
          <p className="mx-auto mt-5 max-w-xl rounded-2xl border border-amber-300/15 bg-amber-300/[0.08] px-5 py-3 text-sm leading-6 text-amber-100">
            By using AI Career Mentor you agree to these
            terms. For questions contact{" "}
            <span className="font-bold text-amber-50">
              support@aicareermentor.co.uk
            </span>
            .
          </p>
        </section>

        {/* Body */}
        <section className="mx-auto max-w-5xl px-4 pb-24 sm:px-6">
          <div className="grid gap-10 lg:grid-cols-[1fr_300px]">

            {/* Main column */}
            <div className="space-y-10">

              {/* Core terms */}
              <div>
                <h2 className="mb-2 text-2xl font-bold tracking-tight sm:text-3xl">
                  How the service works.
                </h2>
                <p className="mb-6 text-sm leading-7 text-gray-400">
                  These terms apply to all users of AI Career Mentor.
                </p>
                <div className="grid gap-5 sm:grid-cols-2">
                  {coreSections.map((item) => (
                    <div
                      key={item.title}
                      className="rounded-[2rem] border border-white/[0.08] bg-white/[0.03] p-6"
                    >
                      <p className="mb-2 font-bold text-white">{item.title}</p>
                      <p className="text-sm leading-7 text-gray-400">{item.text}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Limitations */}
              <div>
                <h2 className="mb-2 text-2xl font-bold tracking-tight sm:text-3xl">
                  What we do not provide.
                </h2>
                <p className="mb-6 text-sm leading-7 text-gray-400">
                  Please read these carefully before relying on AI-generated feedback.
                </p>
                <div className="grid gap-5 sm:grid-cols-2">
                  {limitations.map((item) => (
                    <div
                      key={item.title}
                      className="rounded-[2rem] border border-white/[0.08] bg-white/[0.03] p-6"
                    >
                      <p className="mb-2 font-bold text-white">{item.title}</p>
                      <p className="text-sm leading-7 text-gray-400">{item.text}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Uploads */}
              <div>
                <h2 className="mb-6 text-2xl font-bold tracking-tight sm:text-3xl">
                  What you upload to AI Career Mentor.
                </h2>
                <div className="rounded-[2rem] border border-white/[0.08] bg-white/[0.03] p-7 space-y-4 text-sm leading-7 text-gray-300">
                  <p>
                    You should only upload or enter information that you are
                    comfortable using for interview practice. This includes CV
                    text, role specifications and interview goal notes.
                  </p>
                  <p>
                    Uploaded files (PDF, Word, text) are converted into plain
                    text for personalisation. Extracted text may not perfectly
                    reproduce the original document, particularly for
                    complex-formatted CVs.
                  </p>
                  <p>
                    Do not upload documents containing confidential employer
                    information, third-party personal data, or sensitive
                    information that is not necessary for interview preparation.
                  </p>
                  <p>
                    AI Career Mentor does not retain raw uploaded files. Only
                    extracted text that you choose to save to your profile is
                    stored.
                  </p>
                </div>
              </div>

              {/* Intellectual property */}
              <div>
                <h2 className="mb-6 text-2xl font-bold tracking-tight sm:text-3xl">
                  Ownership and protection of the platform.
                </h2>
                <div className="rounded-[2rem] border border-white/[0.08] bg-white/[0.03] p-7 space-y-4 text-sm leading-7 text-gray-300">
                  <p>
                    The AI Career Mentor platform (including its source code,
                    software architecture, user interface design, visual design,
                    branding, copy, question library, scoring methodology, AI
                    coaching systems, prompts, workflows, and all other technology)
                    is the exclusive property of AI Career Mentor Ltd and is
                    protected by copyright, database rights, and other intellectual
                    property laws of England and Wales and applicable international
                    treaties.
                  </p>
                  <p>
                    The name{" "}
                    <strong className="text-white">AI Career Mentor</strong>, the
                    associated logo, and all related brand assets are trade marks
                    of AI Career Mentor Ltd. You may not use our name, logo, or
                    branding in any way without prior written consent.
                  </p>
                  <p>
                    You retain ownership of personal content you provide (CV text,
                    interview answers, goal notes). By submitting content to the
                    platform, you grant AI Career Mentor Ltd a limited, non-exclusive,
                    royalty-free licence to process and store that content solely
                    for the purpose of delivering the service to you.
                  </p>
                  <p>
                    AI-generated outputs, including feedback, scores, model
                    answers, and session summaries, are generated by AI Career
                    Mentor Ltd&apos;s systems and are provided for your personal
                    interview preparation only. You may not redistribute, resell,
                    sublicence, or incorporate these outputs into any commercial
                    product or service.
                  </p>
                </div>
              </div>

              {/* Prohibited use */}
              <div>
                <h2 className="mb-2 text-2xl font-bold tracking-tight sm:text-3xl">
                  What you must not do.
                </h2>
                <p className="mb-6 text-sm leading-7 text-gray-400">
                  The following are strictly prohibited and may result in
                  immediate termination of your access and legal action.
                </p>
                <div className="grid gap-5 sm:grid-cols-2">
                  {prohibitedUse.map((item) => (
                    <div
                      key={item.title}
                      className="rounded-[2rem] border border-white/[0.08] bg-white/[0.03] p-6"
                    >
                      <p className="mb-2 font-bold text-white">{item.title}</p>
                      <p className="text-sm leading-6 text-gray-400">{item.text}</p>
                    </div>
                  ))}
                </div>
                <p className="mt-5 rounded-2xl border border-red-400/15 bg-red-400/[0.07] p-4 text-sm leading-6 text-red-200">
                  AI Career Mentor Ltd reserves the right to pursue all available
                  legal remedies, including injunctive relief and damages,
                  against any individual or organisation found to be in violation
                  of these terms.
                </p>
              </div>

              {/* Governing law */}
              <div>
                <h2 className="mb-6 text-2xl font-bold tracking-tight sm:text-3xl">
                  Jurisdiction and disputes.
                </h2>
                <div className="rounded-[2rem] border border-white/[0.08] bg-white/[0.03] p-7 space-y-4 text-sm leading-7 text-gray-300">
                  <p>
                    These terms are governed by the laws of England and Wales. Any
                    disputes arising under these terms shall be subject to the
                    exclusive jurisdiction of the courts of England and Wales.
                  </p>
                  <p>
                    AI Career Mentor Ltd is a company registered in England &amp; Wales
                    (Company No. 17288119).
                  </p>
                  <p>
                    If any provision of these terms is found to be unenforceable,
                    the remaining provisions will continue to apply.
                  </p>
                </div>
              </div>

            </div>

            {/* Sidebar */}
            <aside className="space-y-6">

              <div className="rounded-[2rem] border border-white/[0.08] bg-white/[0.03] p-6">
                <p className="mb-4 text-[11px] font-bold tracking-wide text-purple-200">
                  Responsible use
                </p>
                <div className="space-y-3 text-sm leading-6 text-gray-400">
                  {responsibleUse.map((item) => (
                    <p key={item} className="flex gap-2">
                      <span className="mt-0.5 shrink-0 text-purple-400">✓</span>
                      <span>{item}</span>
                    </p>
                  ))}
                </div>
              </div>

              <div className="rounded-[2rem] border border-white/[0.08] bg-white/[0.03] p-6">
                <p className="mb-4 text-[11px] font-bold tracking-wide text-purple-200">
                  Quick links
                </p>
                <div className="space-y-3">
                  <Link href="/for-candidates/sign-up">
                    <button className="w-full rounded-2xl bg-gradient-to-r from-violet-600 to-purple-600 px-5 py-3 text-sm font-bold text-white shadow-lg transition hover:scale-[1.02]">
                      Start free
                    </button>
                  </Link>
                  <Link href="/privacy">
                    <button className="w-full rounded-2xl border border-white/[0.08] bg-white/[0.03] px-5 py-3 text-sm font-bold text-gray-300 transition hover:bg-white/[0.06]">
                      Privacy policy
                    </button>
                  </Link>
                  <Link href="/contact">
                    <button className="w-full rounded-2xl border border-white/[0.08] bg-white/[0.03] px-5 py-3 text-sm font-bold text-gray-300 transition hover:bg-white/[0.06]">
                      Contact us
                    </button>
                  </Link>
                </div>
              </div>

              <div className="rounded-[2rem] border border-white/[0.08] bg-white/[0.03] p-6">
                <p className="mb-3 text-[11px] font-bold tracking-wide text-purple-200">
                  Questions about these terms
                </p>
                <p className="mb-2 text-sm leading-6 text-gray-400">
                  Contact us at:
                </p>
                <p className="font-bold text-gray-200">
                  support@aicareermentor.co.uk
                </p>
              </div>

            </aside>
          </div>
        </section>
      </div>
    </CandidateShell>
  );
}
